/**
 * POST /api/stories/draft-from-evidence
 * body: { id: string, replace?: boolean }
 *
 * Assembles the full evidence picture (same as /api/stories/evidence),
 * formats it as a markdown receipts brief, writes it to the story's
 * editorial_notes, and flips state candidate→draft (or leaves state alone
 * if already past candidate).
 *
 * Per Rule 4 (CLAUDE.md): the brief is RECEIPTS ONLY. Editorial framing
 * sections in the brief are placeholders for David / Research Claude to
 * fill in. No factual claims are generated by AI here.
 *
 * Default behavior preserves any existing editorial_notes by appending the
 * brief beneath them, separated by a horizontal rule. Pass replace:true to
 * overwrite (e.g. when re-generating after canonical-store changes).
 */
import { NextRequest, NextResponse } from "next/server"
import { requireAdmin } from "@/lib/auth"
import { getGraph } from "@/lib/donor-map-singleton"
import { buildFullEvidence, formatBrief } from "@/lib/story-evidence"
import path from "path"
import fs from "fs"

export const dynamic = "force-dynamic"

function findRepoRoot(startDir: string): string {
  let dir = startDir
  for (let i = 0; i < 8; i++) {
    if (fs.existsSync(path.join(dir, "data", "stories.jsonl"))) return dir
    if (fs.existsSync(path.join(dir, ".git"))) return dir
    const parent = path.dirname(dir)
    if (parent === dir) break
    dir = parent
  }
  return startDir
}

const REPO_ROOT = findRepoRoot(process.cwd())
const STORIES_FILE = path.join(REPO_ROOT, "data", "stories.jsonl")

function loadStories(): any[] {
  if (!fs.existsSync(STORIES_FILE)) return []
  return fs
    .readFileSync(STORIES_FILE, "utf-8")
    .split(/\r?\n/)
    .filter(Boolean)
    .map((l) => { try { return JSON.parse(l) } catch { return null } })
    .filter(Boolean)
}

function persistStories(stories: any[]): void {
  const tmp = STORIES_FILE + ".tmp"
  const lines = stories.map((r) => JSON.stringify(r))
  fs.writeFileSync(tmp, lines.join("\n") + (lines.length ? "\n" : ""), "utf-8")
  fs.renameSync(tmp, STORIES_FILE)
}

export async function POST(req: NextRequest) {
  const gate = await requireAdmin(req)
  if (!gate.ok) return gate.response

  let body: Record<string, unknown>
  try { body = await req.json() } catch {
    return NextResponse.json({ error: "invalid JSON body" }, { status: 400 })
  }
  const id = typeof body.id === "string" ? body.id : null
  const replace = body.replace === true
  if (!id) return NextResponse.json({ error: "id (string) is required" }, { status: 400 })

  const stories = loadStories()
  const idx = stories.findIndex((s) => s.id === id)
  if (idx === -1) return NextResponse.json({ error: `story ${id} not found` }, { status: 404 })
  const story = stories[idx]

  const graph = getGraph()
  if (!graph) {
    return NextResponse.json(
      { error: "Librarian unavailable (canonical stores failed to load)." },
      { status: 503 },
    )
  }

  const evidence = buildFullEvidence(graph, story)
  if (!evidence) {
    return NextResponse.json(
      { error: "Could not build evidence for this story." },
      { status: 500 },
    )
  }
  const brief = formatBrief(evidence, story)

  // Compose new editorial_notes
  const previous = typeof story.editorial_notes === "string" ? story.editorial_notes.trim() : ""
  let nextNotes: string
  if (replace || !previous) {
    nextNotes = brief
  } else {
    // Don't double-stack briefs — if the previous notes already contain the
    // auto-brief header, swap that section out instead of appending again.
    const HEADER = "## Evidence brief"
    const HEADER_IDX = previous.indexOf(HEADER)
    if (HEADER_IDX !== -1) {
      nextNotes = previous.slice(0, HEADER_IDX).trimEnd() + "\n\n" + brief
    } else {
      nextNotes = previous + "\n\n---\n\n" + brief
    }
  }

  // State flip: candidate → draft. Already past candidate? Leave it alone.
  const STATE_ORDER = ["candidate", "draft", "ready", "published"]
  const curStateIdx = STATE_ORDER.indexOf(story.state)
  const targetStateIdx = STATE_ORDER.indexOf("draft")
  const newState = curStateIdx >= 0 && curStateIdx < targetStateIdx ? "draft" : story.state

  const now = new Date().toISOString()
  const merged = {
    ...story,
    editorial_notes: nextNotes,
    state: newState,
    last_updated: now,
  }
  stories[idx] = merged
  persistStories(stories)

  return NextResponse.json({
    story: merged,
    state_changed: newState !== story.state,
    previous_state: story.state,
    evidence_summary: {
      money_for_total: evidence.pair.money_for.total_amount,
      money_against_total: evidence.pair.money_against.total_amount,
      money_for_edges: evidence.pair.money_for.edge_count,
      money_against_edges: evidence.pair.money_against.edge_count,
      shared_donors_count: evidence.shared_donors.length,
      cross_targets_count: evidence.cross_targets.length,
      unresolved_reason: evidence.pair.unresolved_reason,
    },
  })
}
