/**
 * GET /api/system-health — serves the ops-surface manifest
 *
 * Reads ops/src/data/ops-surfaces.json (generated by
 * scripts/ops-surface-audit.cjs) and returns it as JSON. The
 * /system-health dashboard page consumes this to render its cards.
 *
 * Live health checks (HTTP status of each page + API route) happen
 * CLIENT-SIDE — the browser hits each URL directly and records the
 * response. The server just provides the static inventory.
 *
 * Why split it this way:
 *   - Server-side fetching of localhost URLs from inside a Next.js
 *     route has bootstrapping issues (the route that's checking has
 *     to call itself). Client-side avoids that loop entirely.
 *   - Client sees real network latency, CORS, auth cookies etc — a
 *     more honest check of what David's browser would actually hit.
 *   - Static manifest + dynamic live-check = fast initial render,
 *     progressive reveal as checks complete.
 *
 * Auth: requireAdmin.
 */

import { NextRequest, NextResponse } from "next/server"
import { requireAdmin } from "@/lib/auth"
import path from "path"
import fs from "fs"

export const dynamic = "force-dynamic"

function findRepoRoot(startDir: string): string {
  let dir = startDir
  for (let i = 0; i < 8; i++) {
    if (fs.existsSync(path.join(dir, "ops", "src", "data", "ops-surfaces.json"))) return dir
    if (fs.existsSync(path.join(dir, ".git"))) return dir
    const parent = path.dirname(dir)
    if (parent === dir) break
    dir = parent
  }
  return startDir
}

const REPO_ROOT = findRepoRoot(process.cwd())
const MANIFEST_PATH = path.join(
  REPO_ROOT,
  "ops",
  "src",
  "data",
  "ops-surfaces.json",
)

export async function GET(req: NextRequest) {
  const gate = await requireAdmin(req)
  if (!gate.ok) return gate.response

  if (!fs.existsSync(MANIFEST_PATH)) {
    return NextResponse.json(
      {
        error: "manifest not found",
        hint: "run 'node scripts/ops-surface-audit.cjs --write' to generate",
      },
      { status: 500 },
    )
  }

  try {
    const raw = fs.readFileSync(MANIFEST_PATH, "utf-8")
    const manifest = JSON.parse(raw)
    return NextResponse.json(manifest)
  } catch (err: any) {
    return NextResponse.json(
      { error: `failed to read manifest: ${err.message}` },
      { status: 500 },
    )
  }
}
