"use client"

/**
 * /system-health — Ops system health dashboard (Pillar 3)
 *
 * Visual inventory of every Ops page + API route with live health
 * status. David opens this once per session and sees what's broken
 * vs what's working at a glance.
 *
 * Data flow:
 *   1. On mount: GET /api/system-health returns the static manifest
 *      (from ops/src/data/ops-surfaces.json, generated by the
 *      ops-surface-audit script)
 *   2. For each page: client-side fetch(route, HEAD) records HTTP status
 *   3. For each API route: client-side fetch(route) records status
 *   4. Results update in place — spinner → color-coded status
 *
 * Status coding:
 *   🟢 green  — page returns 200 (or 307/308 redirect to valid target)
 *              or API returns 200/401/403 (gating firing correctly)
 *   🟡 yellow — page returns 5xx OR API returns 5xx
 *   🔴 red    — fetch crashed (network error, CORS block, etc.)
 *   ⚫ gray   — not yet checked
 *
 * No writes, no side effects. Safe to refresh. Admin-only.
 */

import { useState, useEffect, useCallback, useRef } from "react"

interface PageSurface {
  route: string
  label: string
  file: string
  type: "page"
  api_dependencies: string[]
  in_sidebar: boolean
}

interface ApiSurface {
  route: string
  file: string
  type: "api"
  methods: string[]
  auth: string
}

interface Manifest {
  generated_at: string
  stats: {
    total_pages: number
    pages_in_sidebar: number
    orphan_pages: number
    total_api_routes: number
    public_apis: number
    admin_apis: number
    tier_apis: number
    orphan_dependencies: number
  }
  pages: PageSurface[]
  api_routes: ApiSurface[]
  orphan_dependencies: string[]
}

type HealthStatus = "unknown" | "checking" | "green" | "yellow" | "red"

interface CheckResult {
  status: HealthStatus
  httpStatus?: number
  error?: string
  checkedAt?: number
}

// ─── Health check helpers ──────────────────────────────────────────

// Skips dynamic routes with params (we can't know what slug to use)
function isCheckable(route: string): boolean {
  return !route.includes(":") && route !== "/sign-in" && route !== "/sign-up"
}

async function checkPage(route: string): Promise<CheckResult> {
  try {
    const res = await fetch(route, {
      method: "GET",
      credentials: "include",
      redirect: "manual",
    })
    const status = res.status
    // 2xx / 3xx = green, 5xx = yellow, everything else (incl 4xx) = yellow
    let health: HealthStatus = "yellow"
    if (status >= 200 && status < 400) health = "green"
    if (status >= 500) health = "yellow"
    return { status: health, httpStatus: status, checkedAt: Date.now() }
  } catch (err: any) {
    return {
      status: "red",
      error: err?.message || String(err),
      checkedAt: Date.now(),
    }
  }
}

async function checkApi(route: string): Promise<CheckResult> {
  try {
    const res = await fetch(route, {
      method: "GET",
      credentials: "include",
    })
    const status = res.status
    // For APIs: 200/401/403 = green (gate firing correctly),
    // 404 = yellow (route file missing or disabled),
    // 5xx = red (server error)
    let health: HealthStatus = "yellow"
    if (status === 200 || status === 401 || status === 403) health = "green"
    if (status >= 500) health = "red"
    return { status: health, httpStatus: status, checkedAt: Date.now() }
  } catch (err: any) {
    return {
      status: "red",
      error: err?.message || String(err),
      checkedAt: Date.now(),
    }
  }
}

// ─── Component ─────────────────────────────────────────────────────

export default function SystemHealthPage() {
  const [manifest, setManifest] = useState<Manifest | null>(null)
  const [loading, setLoading] = useState(true)
  const [manifestError, setManifestError] = useState<string | null>(null)
  const [pageChecks, setPageChecks] = useState<Record<string, CheckResult>>({})
  const [apiChecks, setApiChecks] = useState<Record<string, CheckResult>>({})
  const [expanded, setExpanded] = useState<Set<string>>(new Set())
  const [running, setRunning] = useState(false)
  const runRef = useRef(0)

  // Load manifest
  useEffect(() => {
    let cancelled = false
    setLoading(true)
    fetch("/api/system-health", { credentials: "include" })
      .then(async (r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`)
        return r.json()
      })
      .then((data: Manifest) => {
        if (cancelled) return
        setManifest(data)
      })
      .catch((err) => {
        if (cancelled) return
        setManifestError(err.message || String(err))
      })
      .finally(() => {
        if (!cancelled) setLoading(false)
      })
    return () => {
      cancelled = true
    }
  }, [])

  // Run all health checks
  const runChecks = useCallback(async () => {
    if (!manifest || running) return
    setRunning(true)
    const thisRun = ++runRef.current

    // Reset states to "checking"
    const initPages: Record<string, CheckResult> = {}
    for (const p of manifest.pages) {
      initPages[p.route] = { status: isCheckable(p.route) ? "checking" : "unknown" }
    }
    setPageChecks(initPages)

    const initApis: Record<string, CheckResult> = {}
    for (const a of manifest.api_routes) {
      initApis[a.route] = { status: isCheckable(a.route) ? "checking" : "unknown" }
    }
    setApiChecks(initApis)

    // Fire page checks in parallel, update state as each returns
    await Promise.all(
      manifest.pages.map(async (p) => {
        if (!isCheckable(p.route)) return
        const result = await checkPage(p.route)
        if (runRef.current !== thisRun) return
        setPageChecks((prev) => ({ ...prev, [p.route]: result }))
      }),
    )

    await Promise.all(
      manifest.api_routes.map(async (a) => {
        if (!isCheckable(a.route)) return
        const result = await checkApi(a.route)
        if (runRef.current !== thisRun) return
        setApiChecks((prev) => ({ ...prev, [a.route]: result }))
      }),
    )

    setRunning(false)
  }, [manifest, running])

  // Auto-run once manifest loads
  useEffect(() => {
    if (manifest && !running && Object.keys(pageChecks).length === 0) {
      runChecks()
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [manifest])

  // Derived stats
  const pageStats = computeStats(pageChecks, manifest?.pages.length || 0)
  const apiStats = computeStats(apiChecks, manifest?.api_routes.length || 0)

  function toggleExpand(key: string) {
    setExpanded((prev) => {
      const next = new Set(prev)
      if (next.has(key)) next.delete(key)
      else next.add(key)
      return next
    })
  }

  if (loading) {
    return (
      <div className="p-8 text-neutral-400 font-mono text-sm">
        Loading system health manifest...
      </div>
    )
  }
  if (manifestError || !manifest) {
    return (
      <div className="p-8">
        <div className="bg-red-900/30 border border-red-700 text-red-200 p-4 font-mono text-sm">
          Error loading manifest: {manifestError || "unknown"}
        </div>
        <div className="mt-4 font-mono text-xs text-neutral-400">
          Try running:{" "}
          <code className="text-amber-400">
            node scripts/ops-surface-audit.cjs --write
          </code>
        </div>
      </div>
    )
  }

  return (
    <div className="p-6 max-w-6xl mx-auto">
      {/* Header */}
      <div className="mb-6 flex items-start justify-between">
        <div>
          <h1 className="text-3xl font-bold text-white mb-1">System Health</h1>
          <p className="text-sm text-neutral-400">
            Ops surface audit · Pillar 3 foundation work · ADR-0009
          </p>
          <p className="text-xs text-neutral-500 mt-1">
            Manifest generated:{" "}
            {new Date(manifest.generated_at).toLocaleString()} · Run{" "}
            <code className="text-amber-400">
              node scripts/ops-surface-audit.cjs --write
            </code>{" "}
            after adding new pages.
          </p>
        </div>
        <button
          onClick={runChecks}
          disabled={running}
          className="px-4 py-2 text-sm border border-amber-700 bg-amber-900/30 text-amber-200 hover:bg-amber-900/60 rounded disabled:opacity-40"
        >
          {running ? "Checking..." : "Re-run checks"}
        </button>
      </div>

      {/* Top-level stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-6">
        <StatCard
          label="Pages"
          value={`${pageStats.green}/${manifest.pages.length}`}
          sub="loaded 200"
          color={pageStats.red > 0 ? "red" : pageStats.yellow > 0 ? "yellow" : "green"}
        />
        <StatCard
          label="API routes"
          value={`${apiStats.green}/${manifest.api_routes.length}`}
          sub="responding cleanly"
          color={apiStats.red > 0 ? "red" : apiStats.yellow > 0 ? "yellow" : "green"}
        />
        <StatCard
          label="Admin-gated"
          value={`${manifest.stats.admin_apis}`}
          sub={`of ${manifest.stats.total_api_routes} API routes`}
          color="neutral"
        />
        <StatCard
          label="⚠ Public (no auth)"
          value={`${manifest.stats.public_apis}`}
          sub="routes with no requireTier/requireAdmin"
          color={manifest.stats.public_apis > 20 ? "yellow" : "neutral"}
        />
      </div>

      {/* Orphan findings */}
      {manifest.orphan_dependencies.length > 0 && (
        <div className="mb-6 bg-neutral-900 border border-neutral-700 rounded p-4">
          <div className="font-mono text-xs text-amber-400 font-bold mb-2">
            ⚠ Orphan page→API dependencies
          </div>
          <div className="font-mono text-xs text-neutral-400 space-y-1">
            {manifest.orphan_dependencies.map((od, i) => (
              <div key={i}>· {od}</div>
            ))}
          </div>
        </div>
      )}

      {/* Pages section */}
      <Section
        title="Pages"
        count={manifest.pages.length}
        checks={pageChecks}
      >
        {manifest.pages.map((p) => {
          const check = pageChecks[p.route] || { status: "unknown" }
          const isExpanded = expanded.has(`page:${p.route}`)
          return (
            <SurfaceRow
              key={p.route}
              route={p.route}
              label={p.label}
              file={p.file}
              check={check}
              isExpanded={isExpanded}
              onToggle={() => toggleExpand(`page:${p.route}`)}
              extra={
                <div className="text-xs text-neutral-500 mt-1">
                  {p.in_sidebar ? (
                    <span>in sidebar</span>
                  ) : (
                    <span className="text-amber-400">⚠ not in sidebar</span>
                  )}
                  {p.api_dependencies.length > 0 && (
                    <span className="ml-3">
                      {p.api_dependencies.length} API deps
                    </span>
                  )}
                </div>
              }
              details={
                <div className="mt-3 space-y-1 font-mono text-xs">
                  <div className="text-neutral-400">File: <code>{p.file}</code></div>
                  {p.api_dependencies.length > 0 && (
                    <div>
                      <div className="text-neutral-400 mt-2 mb-1">API dependencies:</div>
                      {p.api_dependencies.map((dep) => (
                        <div key={dep} className="text-neutral-500">· {dep}</div>
                      ))}
                    </div>
                  )}
                </div>
              }
            />
          )
        })}
      </Section>

      {/* API routes section */}
      <Section
        title="API routes"
        count={manifest.api_routes.length}
        checks={apiChecks}
      >
        {manifest.api_routes.map((a) => {
          const check = apiChecks[a.route] || { status: "unknown" }
          const isExpanded = expanded.has(`api:${a.route}`)
          return (
            <SurfaceRow
              key={a.route}
              route={a.route}
              label={a.methods.join(", ") || "?"}
              file={a.file}
              check={check}
              isExpanded={isExpanded}
              onToggle={() => toggleExpand(`api:${a.route}`)}
              extra={
                <div className="text-xs text-neutral-500 mt-1">
                  auth:{" "}
                  <span className={authColor(a.auth)}>{a.auth}</span>
                </div>
              }
              details={
                <div className="mt-3 space-y-1 font-mono text-xs">
                  <div className="text-neutral-400">File: <code>{a.file}</code></div>
                  <div className="text-neutral-400">Methods: {a.methods.join(", ") || "(none detected)"}</div>
                  <div className="text-neutral-400">
                    Auth: <span className={authColor(a.auth)}>{a.auth}</span>
                  </div>
                  {check.httpStatus !== undefined && (
                    <div className="text-neutral-400">
                      Last check: HTTP {check.httpStatus}
                    </div>
                  )}
                  {check.error && (
                    <div className="text-red-400">Error: {check.error}</div>
                  )}
                </div>
              }
            />
          )
        })}
      </Section>
    </div>
  )
}

// ─── Helper components ──────────────────────────────────────────────

function computeStats(checks: Record<string, CheckResult>, total: number) {
  let green = 0,
    yellow = 0,
    red = 0,
    unknown = 0,
    checking = 0
  for (const r of Object.values(checks)) {
    if (r.status === "green") green++
    else if (r.status === "yellow") yellow++
    else if (r.status === "red") red++
    else if (r.status === "checking") checking++
    else unknown++
  }
  return { green, yellow, red, unknown, checking, total }
}

function authColor(auth: string): string {
  if (auth === "admin") return "text-amber-400"
  if (auth?.startsWith("tier:")) return "text-blue-400"
  if (auth === "public") return "text-neutral-400"
  return "text-neutral-500"
}

function statusDot(status: HealthStatus): string {
  if (status === "green") return "bg-green-500"
  if (status === "yellow") return "bg-amber-500"
  if (status === "red") return "bg-red-500"
  if (status === "checking") return "bg-blue-500 animate-pulse"
  return "bg-neutral-700"
}

function StatCard({
  label,
  value,
  sub,
  color,
}: {
  label: string
  value: string
  sub: string
  color: "green" | "yellow" | "red" | "neutral"
}) {
  const borderColor =
    color === "green"
      ? "border-green-800"
      : color === "yellow"
        ? "border-amber-800"
        : color === "red"
          ? "border-red-800"
          : "border-neutral-800"
  const valueColor =
    color === "green"
      ? "text-green-400"
      : color === "yellow"
        ? "text-amber-400"
        : color === "red"
          ? "text-red-400"
          : "text-white"
  return (
    <div className={`bg-neutral-900 border ${borderColor} rounded p-4`}>
      <div className="text-xs text-neutral-400 font-mono uppercase">{label}</div>
      <div className={`text-2xl font-bold ${valueColor} mt-1`}>{value}</div>
      <div className="text-xs text-neutral-500 mt-1">{sub}</div>
    </div>
  )
}

function Section({
  title,
  count,
  checks,
  children,
}: {
  title: string
  count: number
  checks: Record<string, CheckResult>
  children: React.ReactNode
}) {
  const stats = computeStats(checks, count)
  return (
    <div className="mb-6">
      <div className="flex items-center justify-between mb-2">
        <h2 className="text-lg font-bold text-white">
          {title} <span className="text-neutral-500 font-normal">({count})</span>
        </h2>
        <div className="font-mono text-xs space-x-3">
          <span className="text-green-400">{stats.green} green</span>
          <span className="text-amber-400">{stats.yellow} yellow</span>
          <span className="text-red-400">{stats.red} red</span>
          <span className="text-neutral-500">{stats.unknown} unknown</span>
        </div>
      </div>
      <div className="space-y-1">{children}</div>
    </div>
  )
}

function SurfaceRow({
  route,
  label,
  file,
  check,
  isExpanded,
  onToggle,
  extra,
  details,
}: {
  route: string
  label: string
  file: string
  check: CheckResult
  isExpanded: boolean
  onToggle: () => void
  extra?: React.ReactNode
  details?: React.ReactNode
}) {
  return (
    <div
      className="bg-neutral-900 border border-neutral-800 hover:border-neutral-700 rounded cursor-pointer"
      onClick={onToggle}
    >
      <div className="p-3 flex items-center gap-3">
        <div className={`w-3 h-3 rounded-full flex-shrink-0 ${statusDot(check.status)}`} />
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-3">
            <code className="text-sm text-white font-mono">{route}</code>
            <span className="text-xs text-neutral-500">{label}</span>
          </div>
          {extra}
        </div>
        <div className="text-xs font-mono text-neutral-500 flex-shrink-0">
          {check.httpStatus !== undefined ? `HTTP ${check.httpStatus}` : check.status}
        </div>
      </div>
      {isExpanded && details && (
        <div className="border-t border-neutral-800 px-3 pb-3">{details}</div>
      )}
    </div>
  )
}
