/**
 * GET /api/bugs — serves the bugs manifest for the /bugs dashboard
 *
 * Reads ops/src/data/bugs-manifest.json (generated by
 * scripts/bug-queue-parser.cjs). Contains:
 *   - bug_queue: entries from content/Admin Notes/bug-queue.md
 *   - deferred_items: entries from content/Phases/phase-6/deferred-items.md
 *   - stats: aggregate counts across both sources
 *
 * No triage writes in v1 — the /bugs page is read-only. Triage
 * happens by David editing the markdown files directly in his editor
 * of choice. A v2 could add write-back actions that update specific
 * fields in the markdown, but that's scope creep for Pillar 5.
 *
 * Auth: requireAdmin.
 */

import { NextRequest, NextResponse } from "next/server"
import { requireAdmin } from "@/lib/auth"
import path from "path"
import fs from "fs"

export const dynamic = "force-dynamic"

function findRepoRoot(startDir: string): string {
  let dir = startDir
  for (let i = 0; i < 8; i++) {
    if (fs.existsSync(path.join(dir, "ops", "src", "data", "bugs-manifest.json"))) return dir
    if (fs.existsSync(path.join(dir, ".git"))) return dir
    const parent = path.dirname(dir)
    if (parent === dir) break
    dir = parent
  }
  return startDir
}

const REPO_ROOT = findRepoRoot(process.cwd())
const MANIFEST_PATH = path.join(
  REPO_ROOT,
  "ops",
  "src",
  "data",
  "bugs-manifest.json",
)

export async function GET(req: NextRequest) {
  const gate = await requireAdmin(req)
  if (!gate.ok) return gate.response

  if (!fs.existsSync(MANIFEST_PATH)) {
    return NextResponse.json(
      {
        error: "bugs manifest not found",
        hint: "run 'node scripts/bug-queue-parser.cjs --write' to generate",
      },
      { status: 500 },
    )
  }

  try {
    const raw = fs.readFileSync(MANIFEST_PATH, "utf-8")
    const manifest = JSON.parse(raw)
    return NextResponse.json(manifest)
  } catch (err: any) {
    return NextResponse.json(
      { error: `failed to read manifest: ${err.message}` },
      { status: 500 },
    )
  }
}
