import { QuartzComponent, QuartzComponentConstructor } from "./types"

/**
 * ProfileSearch — autocomplete search input for donors, politicians,
 * PACs, etc. Renders in two locations (left sidebar + homepage hero)
 * via the `placement` prop: "sidebar" is compact; "hero" is prominent.
 *
 * Data source: public/static/profile-index.json, generated by
 * scripts/build-profile-search-index.cjs during ci-prebuild.
 *
 * Public vs local filtering: client-side, based on hostname.
 *   - localhost + *.local → show every entity regardless of readiness
 *   - thedonormap.org → only entities with readiness in
 *     {ready, data-complete, verified} (drafts stay local)
 *
 * Scoring: exact name match → prefix match → token substring match.
 * No external library; ~1500 entries sorted alphabetically.
 */

// ProfileSearch is a "wiring-only" component: renders no server-side
// JSX, just registers the afterDOMLoaded init script + the global
// SCSS. The actual search input markup is inlined directly in
// LandingPage (hero placement) and DonorMapSidebar (sidebar). Both
// use the same data-profile-search-root attribute so the single init
// script hooks up every instance.
const ProfileSearch: QuartzComponent = () => null
ProfileSearch.afterDOMLoaded = buildInlineScript()

// Inline script is identical across placements; only the root element
// selector varies by scoping via data-placement attribute.
function buildInlineScript(): string {
  return `
(function() {
  var INDEX_URL = '/static/profile-index.json';
  var indexPromise = null;

  // Readiness tiers that are publicly searchable on the deployed site.
  // Drafts stay local-only. Until entities.jsonl is synced with
  // ADR-0017's 5-tier system, 'ready' is the practical publishable
  // bar (data-complete + verified will be added once that sync lands).
  var PUBLIC_READINESS = { 'ready': 1, 'data-complete': 1, 'verified': 1 };

  function isLocalHost() {
    var h = location.hostname;
    return h === 'localhost' || h === '127.0.0.1' || h.endsWith('.local') || h.endsWith('.localhost') || h === '';
  }

  function loadIndex() {
    if (indexPromise) return indexPromise;
    indexPromise = fetch(INDEX_URL)
      .then(function(r) { return r.ok ? r.json() : { entries: [] }; })
      .then(function(j) {
        var entries = (j && j.entries) || [];
        // Apply public filter at load time so every search doesn't
        // re-filter. Dev = full set; prod = ready+ only.
        if (!isLocalHost()) {
          entries = entries.filter(function(e) { return PUBLIC_READINESS[e.readiness] === 1; });
        }
        return entries;
      })
      .catch(function() { return []; });
    return indexPromise;
  }

  function esc(s) {
    return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;');
  }

  // Scoring: exact match = 100, prefix = 80, word-start = 60,
  // substring = 40. Penalize on name length (shorter matches first).
  function score(entry, q) {
    var n = entry.name.toLowerCase();
    if (n === q) return 100;
    if (n.indexOf(q) === 0) return 80 - Math.min(20, n.length - q.length);
    // Word-start match: "mas" matches "Cortez Masto" at second word
    var words = n.split(/\\s+/);
    for (var i = 0; i < words.length; i++) {
      if (words[i].indexOf(q) === 0) return 60 - i - Math.min(10, n.length / 4);
    }
    if (n.indexOf(q) >= 0) return 40 - Math.min(10, n.length / 5);
    return 0;
  }

  function typeBadge(t) {
    if (!t) return '';
    var map = {
      'politician': 'POL', 'state-politician': 'POL', 'local-politician': 'POL',
      'donor': 'DONOR', 'corporation': 'CORP', 'pac': 'PAC',
      'think-tank': 'THINK', 'lobbying-firm': 'K-ST',
    };
    return map[t] || t.slice(0, 4).toUpperCase();
  }

  function contextLine(e) {
    var bits = [];
    if (e.party) bits.push(e.party);
    if (e.chamber) bits.push(e.chamber);
    if (e.state) bits.push(e.state);
    if (e.sector && !e.party) bits.push(e.sector);
    return bits.join(' · ');
  }

  function renderResults(dropdown, results, activeIdx) {
    if (results.length === 0) {
      dropdown.innerHTML = '<div class="profile-search-empty">No matching profiles.</div>';
      dropdown.hidden = false;
      return;
    }
    var html = '';
    for (var i = 0; i < results.length; i++) {
      var e = results[i];
      var active = i === activeIdx ? ' profile-search-result-active' : '';
      html += '<a class="profile-search-result' + active + '" href="' + esc(e.slug) + '" data-index="' + i + '" role="option">' +
        '<span class="profile-search-badge">' + esc(typeBadge(e.type)) + '</span>' +
        '<span class="profile-search-main">' +
          '<span class="profile-search-name">' + esc(e.name) + '</span>' +
          (contextLine(e) ? '<span class="profile-search-ctx">' + esc(contextLine(e)) + '</span>' : '') +
        '</span>' +
        '</a>';
    }
    dropdown.innerHTML = html;
    dropdown.hidden = false;
  }

  function wireInstance(root) {
    var input = root.querySelector('[data-profile-search-input]');
    var dropdown = root.querySelector('[data-profile-search-dropdown]');
    if (!input || !dropdown) return;

    var state = { results: [], activeIdx: -1 };

    function run(q) {
      q = (q || '').toLowerCase().trim();
      if (q.length < 2) {
        dropdown.hidden = true;
        state.results = [];
        state.activeIdx = -1;
        return;
      }
      loadIndex().then(function(entries) {
        var scored = [];
        for (var i = 0; i < entries.length; i++) {
          var s = score(entries[i], q);
          if (s > 0) scored.push({ e: entries[i], s: s });
        }
        scored.sort(function(a, b) { return b.s - a.s; });
        state.results = scored.slice(0, 8).map(function(x) { return x.e; });
        state.activeIdx = state.results.length > 0 ? 0 : -1;
        renderResults(dropdown, state.results, state.activeIdx);
      });
    }

    input.addEventListener('input', function() { run(input.value); });
    input.addEventListener('focus', function() {
      if (input.value.length >= 2) run(input.value);
    });
    input.addEventListener('blur', function() {
      // Delay hide so click on result fires before dropdown vanishes
      setTimeout(function() { dropdown.hidden = true; }, 150);
    });
    input.addEventListener('keydown', function(ev) {
      if (dropdown.hidden || state.results.length === 0) {
        if (ev.key === 'Enter' && input.value.length >= 2) run(input.value);
        return;
      }
      if (ev.key === 'ArrowDown') {
        ev.preventDefault();
        state.activeIdx = Math.min(state.results.length - 1, state.activeIdx + 1);
        renderResults(dropdown, state.results, state.activeIdx);
      } else if (ev.key === 'ArrowUp') {
        ev.preventDefault();
        state.activeIdx = Math.max(0, state.activeIdx - 1);
        renderResults(dropdown, state.results, state.activeIdx);
      } else if (ev.key === 'Enter') {
        ev.preventDefault();
        var chosen = state.results[state.activeIdx];
        if (chosen) location.href = chosen.slug;
      } else if (ev.key === 'Escape') {
        dropdown.hidden = true;
        input.blur();
      }
    });

    dropdown.addEventListener('click', function(ev) {
      // Let the anchor's default navigation happen; just dismiss
      setTimeout(function() { dropdown.hidden = true; }, 0);
      ev.stopPropagation();
    });
  }

  function init() {
    var roots = document.querySelectorAll('[data-profile-search-root]');
    roots.forEach(wireInstance);
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
`
}

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore — Quartz convention for raw-text SCSS imports
import profileSearchStyle from "./styles/profileSearch.scss"
ProfileSearch.css = profileSearchStyle

export default (() => ProfileSearch) satisfies QuartzComponentConstructor
