"use client"

import { useEffect, useState, useCallback } from "react"

/**
 * Launch 50 Sign-Off Tracker
 *
 * Tracks the 50 curated profiles for the April 30 launch through the
 * editorial sign-off pipeline:
 *   1. Class Analysis written (Research Claude)
 *   2. URLs verified (David)
 *   3. David final review
 *   4. Promoted to content-readiness: verified
 *
 * Reads audit data from content/Admin Notes/launch-50-audit.json
 * (generated by scripts/launch-50-audit.cjs).
 * Writes checklist state to ops/data/launch-50-signoff.json (gitignored).
 */

interface AuditRow {
  name: string
  file?: string
  missing?: boolean
  err?: string
  readiness?: string
  type?: string
  hasClassAnalysis?: boolean
  sourceCount?: number
  urlNeeded?: number
  unverified?: number
  needsReview?: number
  autoBlocks?: number
  hasGaps?: boolean
}

interface SignoffEntry {
  classAnalysisWritten?: boolean
  urlsVerified?: boolean
  davidReviewed?: boolean
  promotedToVerified?: boolean
  notes?: string
  updatedAt?: string
}

type SignoffState = Record<string, SignoffEntry>

interface ApiResponse {
  audit: {
    politicians: AuditRow[]
    donors: AuditRow[]
    corporations: AuditRow[]
  }
  signoff: SignoffState
  auditFileExists: boolean
}

export default function SignoffLaunchPage() {
  const [data, setData] = useState<ApiResponse | null>(null)
  const [loading, setLoading] = useState(true)
  const [filter, setFilter] = useState<"all" | "blockers" | "ready-to-sign">("all")

  const load = useCallback(() => {
    fetch("/api/launch-50")
      .then((r) => r.json())
      .then((d) => {
        setData(d)
        setLoading(false)
      })
      .catch(() => setLoading(false))
  }, [])

  useEffect(() => { load() }, [load])

  const toggleField = async (name: string, field: keyof SignoffEntry, value: boolean) => {
    const res = await fetch("/api/launch-50", {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ name, updates: { [field]: value } }),
    })
    if (res.ok) load()
  }

  if (loading) return <div className="p-8 text-sm text-[var(--color-text-dim)]">Loading launch 50 audit...</div>
  if (!data) return <div className="p-8 text-sm text-[var(--color-red)]">Failed to load audit data.</div>
  if (!data.auditFileExists) {
    return (
      <div className="p-8 max-w-2xl">
        <h1 className="text-2xl font-black mb-4">Launch 50 Sign-Off</h1>
        <p className="text-sm text-[var(--color-text-dim)] mb-4">
          Audit file not found at <code>content/Admin Notes/launch-50-audit.json</code>.
        </p>
        <p className="text-sm text-[var(--color-text-dim)] mb-4">
          Run: <code className="text-[var(--color-yellow)]">node scripts/launch-50-audit.cjs</code>
        </p>
      </div>
    )
  }

  const allRows = [...data.audit.politicians, ...data.audit.donors, ...data.audit.corporations]
  const totalFound = allRows.filter(r => !r.missing && !r.err).length

  // Signoff rollups
  const caWritten = allRows.filter(r => data.signoff[r.name]?.classAnalysisWritten || r.hasClassAnalysis).length
  const urlsVerified = allRows.filter(r => data.signoff[r.name]?.urlsVerified).length
  const davidReviewed = allRows.filter(r => data.signoff[r.name]?.davidReviewed).length
  const promoted = allRows.filter(r => data.signoff[r.name]?.promotedToVerified || r.readiness === "verified").length

  const rowStatus = (r: AuditRow): "ready-to-sign" | "blockers" | "in-progress" | "done" => {
    const s = data.signoff[r.name] || {}
    if (s.promotedToVerified || r.readiness === "verified") return "done"
    const hasCA = s.classAnalysisWritten || r.hasClassAnalysis
    const hasFlags = (r.unverified || 0) + (r.urlNeeded || 0) + (r.needsReview || 0) > 0
    if (hasCA && s.urlsVerified && !hasFlags) return "ready-to-sign"
    if (hasFlags || !hasCA) return "blockers"
    return "in-progress"
  }

  const renderSection = (title: string, rows: AuditRow[]) => {
    const filteredRows = rows.filter(r => {
      if (filter === "all") return true
      if (r.missing || r.err) return false
      const status = rowStatus(r)
      return filter === status
    })
    if (filteredRows.length === 0) return null
    return (
      <div className="mb-8">
        <h2 className="text-sm font-black uppercase tracking-widest mb-3 text-[var(--color-yellow)]">
          {title} ({filteredRows.length})
        </h2>
        <div className="space-y-1">
          {filteredRows.map((r) => {
            if (r.missing || r.err) {
              return (
                <div key={r.name} className="p-2 border border-[var(--color-red)]/30 bg-[var(--color-red)]/5 text-[11px]">
                  <span className="text-[var(--color-red)] font-bold">{r.missing ? "MISSING" : r.err}</span> — {r.name}
                </div>
              )
            }
            const s = data.signoff[r.name] || {}
            const status = rowStatus(r)
            const statusColor =
              status === "done" ? "var(--color-green)" :
              status === "ready-to-sign" ? "var(--color-yellow)" :
              status === "blockers" ? "var(--color-red)" : "var(--color-steel)"

            const hasCA = s.classAnalysisWritten || r.hasClassAnalysis
            const flags: string[] = []
            if (r.urlNeeded) flags.push(`URL:${r.urlNeeded}`)
            if (r.unverified) flags.push(`UNV:${r.unverified}`)
            if (r.needsReview) flags.push(`REV:${r.needsReview}`)
            if (r.hasGaps) flags.push("gaps")

            return (
              <div
                key={r.name}
                className="p-3 border border-[var(--color-border)] bg-[var(--color-bg-card)] text-[11px] font-mono"
                style={{ borderLeft: `3px solid ${statusColor}` }}
              >
                <div className="flex items-center gap-3 mb-2">
                  <span className="font-bold text-[13px] text-[var(--color-text)]">{r.name}</span>
                  <span className="text-[9px] uppercase px-1.5 py-0.5 border border-[var(--color-border)] text-[var(--color-text-dim)]">
                    {r.readiness}
                  </span>
                  <span className="text-[9px] text-[var(--color-text-dim)]">
                    {r.autoBlocks || 0} blocks · {r.sourceCount || 0} sources
                  </span>
                  {flags.length > 0 && (
                    <span className="text-[9px] text-[var(--color-red)] font-bold">
                      {flags.join(" · ")}
                    </span>
                  )}
                  <span className="ml-auto text-[9px] uppercase font-bold" style={{ color: statusColor }}>
                    {status}
                  </span>
                </div>

                <div className="flex items-center gap-4 text-[10px]">
                  <label className="flex items-center gap-1.5 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={!!hasCA}
                      onChange={(e) => toggleField(r.name, "classAnalysisWritten", e.target.checked)}
                      className="cursor-pointer"
                    />
                    <span className={hasCA ? "text-[var(--color-green)]" : "text-[var(--color-text-dim)]"}>
                      Class Analysis
                    </span>
                  </label>
                  <label className="flex items-center gap-1.5 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={!!s.urlsVerified}
                      onChange={(e) => toggleField(r.name, "urlsVerified", e.target.checked)}
                      className="cursor-pointer"
                    />
                    <span className={s.urlsVerified ? "text-[var(--color-green)]" : "text-[var(--color-text-dim)]"}>
                      URLs verified
                    </span>
                  </label>
                  <label className="flex items-center gap-1.5 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={!!s.davidReviewed}
                      onChange={(e) => toggleField(r.name, "davidReviewed", e.target.checked)}
                      className="cursor-pointer"
                    />
                    <span className={s.davidReviewed ? "text-[var(--color-green)]" : "text-[var(--color-text-dim)]"}>
                      David reviewed
                    </span>
                  </label>
                  <label className="flex items-center gap-1.5 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={!!s.promotedToVerified}
                      onChange={(e) => toggleField(r.name, "promotedToVerified", e.target.checked)}
                      className="cursor-pointer"
                    />
                    <span className={s.promotedToVerified ? "text-[var(--color-green)]" : "text-[var(--color-text-dim)]"}>
                      Promoted to verified
                    </span>
                  </label>
                  {r.file && (
                    <a
                      href={`/profile?path=${encodeURIComponent(r.file)}`}
                      className="ml-auto text-[var(--color-steel)] hover:text-[var(--color-yellow)] underline"
                    >
                      open →
                    </a>
                  )}
                </div>
              </div>
            )
          })}
        </div>
      </div>
    )
  }

  return (
    <div className="p-8 max-w-6xl">
      <div className="mb-6">
        <h1 className="text-2xl font-black mb-1 uppercase tracking-widest">Launch 50 Sign-Off</h1>
        <p className="text-[11px] text-[var(--color-text-dim)]">
          Curated profiles for April 30 launch. Track through editorial pipeline to verified tier.
        </p>
      </div>

      {/* Progress bar */}
      <div className="mb-6 p-4 border border-[var(--color-border)] bg-[var(--color-bg-card)]">
        <div className="grid grid-cols-4 gap-4 text-[11px] font-mono">
          <div>
            <div className="text-[var(--color-text-dim)] uppercase text-[9px] mb-1">Class Analysis</div>
            <div className="text-[var(--color-yellow)] text-[18px] font-bold">{caWritten}/{totalFound}</div>
            <div className="h-1 bg-[var(--color-border)] mt-1">
              <div className="h-full bg-[var(--color-yellow)]" style={{ width: `${(caWritten/totalFound)*100}%` }} />
            </div>
          </div>
          <div>
            <div className="text-[var(--color-text-dim)] uppercase text-[9px] mb-1">URLs Verified</div>
            <div className="text-[var(--color-yellow)] text-[18px] font-bold">{urlsVerified}/{totalFound}</div>
            <div className="h-1 bg-[var(--color-border)] mt-1">
              <div className="h-full bg-[var(--color-yellow)]" style={{ width: `${(urlsVerified/totalFound)*100}%` }} />
            </div>
          </div>
          <div>
            <div className="text-[var(--color-text-dim)] uppercase text-[9px] mb-1">David Reviewed</div>
            <div className="text-[var(--color-yellow)] text-[18px] font-bold">{davidReviewed}/{totalFound}</div>
            <div className="h-1 bg-[var(--color-border)] mt-1">
              <div className="h-full bg-[var(--color-yellow)]" style={{ width: `${(davidReviewed/totalFound)*100}%` }} />
            </div>
          </div>
          <div>
            <div className="text-[var(--color-text-dim)] uppercase text-[9px] mb-1">Verified</div>
            <div className="text-[var(--color-green)] text-[18px] font-bold">{promoted}/{totalFound}</div>
            <div className="h-1 bg-[var(--color-border)] mt-1">
              <div className="h-full bg-[var(--color-green)]" style={{ width: `${(promoted/totalFound)*100}%` }} />
            </div>
          </div>
        </div>
      </div>

      {/* Filter tabs */}
      <div className="flex gap-2 mb-4 text-[11px] font-mono">
        {(["all", "blockers", "ready-to-sign"] as const).map((f) => (
          <button
            key={f}
            onClick={() => setFilter(f)}
            className={`px-3 py-1 border ${
              filter === f
                ? "border-[var(--color-yellow)] text-[var(--color-yellow)]"
                : "border-[var(--color-border)] text-[var(--color-text-dim)] hover:text-[var(--color-text)]"
            }`}
          >
            {f}
          </button>
        ))}
      </div>

      {renderSection("Politicians", data.audit.politicians)}
      {renderSection("Donors", data.audit.donors)}
      {renderSection("Corporations", data.audit.corporations)}
    </div>
  )
}
